[[language]]
name = "go"
auto-format = true

[[language]]
name = "haskell"
file-types = ["hs"]
indent = { tab-width = 4, unit = " " }

[[language]]
name = "nix"
auto-format = true
formatter = { command = "alejandra" }
