"ui.background" = "bg"
"ui.background.separator" = "light-gray"
"ui.window"     = "light-gray"
"ui.text"       = "fg"

"ui.cursor" = { fg = "bg", bg = "light-blue" }
"ui.selection" = { fg = "bg", bg = "fg" }

"ui.help"  = {fg = "comment", bg = "selection"}
"ui.menu"  = {fg = "comment", bg = "selection"}
"ui.popup" = {fg = "comment", bg = "selection"}

"ui.statusline" = {fg = "comment", bg = "selection"}
"ui.statusline.normal" = {fg = "selection", bg = "light-yellow"}
"ui.statusline.insert" = {fg = "selection", bg = "light-magenta"}
"ui.statusline.select" = {fg = "selection", bg = "light-blue"}

"ui.gutter" = "light-gray"
"ui.gutter.selected" = "fg"

keyword  = "magenta"
operator = "magenta"
type     = "blue"
constant = "orange"
string   = "green"
function = "light-yellow"
comment  = {fg="comment", modifiers=["italic"]}

"diagnostic.hint"    = { underline = { color = "light-gray", style = "curl" } }
"diagnostic.info"    = { underline = { color = "light-green", style = "curl" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.error"   = { underline = { color = "light-red", style = "curl" } }

error   = "light-red"
warning = "yellow"
info    = "light-green"
hint    = "light-gray"

"diff.plus"  = "#35bf86"
"diff.minus" = "#f22c86"
"diff.delta" = "#6f44f0"

[palette]
bg        = "#1d1f21"
fg        = "#c5c8c6"
hl        = "#81a2be"
line      = "#282a2e"
comment   = "#969896"
selection = "#373b41"

red     = "#cc6666"
green   = "#b5bd68"
yellow  = "#e6c547"
blue    = "#81a2be"
magenta = "#b294bb"
cyan    = "#70c0ba"
orange  = "#de935f"
aqua    = "#8abeb7"
gray    = "#1d1f21"

light-red     = "#ff3334"
light-green   = "#9ec400"
light-yellow  = "#f0c674"
light-blue    = "#81a2be"
light-magenta = "#b77ee0"
light-cyan    = "#54ced6"
light-gray    = "#666666"
